version: '2.1'
services:
  postgres:
    restart: always
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=psxtree
      - POSTGRES_PASSWORD=psxtree
      - POSTGRES_DB=groudon
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  psxtree:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - .:/psxtree
    entrypoint: ["python", "unittest.py"]
